############################################################
#
# Home Assistant Media Players
#
############################################################

- platform: cast
  host: 192.168.250.60
- platform: cast
  host: 192.168.250.61
